# Generated by Django 5.1.15 on 2026-02-21 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("zip", models.CharField(max_length=10)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("single_family", "Single Family"),
                            ("multi_family", "Multi Family"),
                            ("condo", "Condo"),
                            ("townhouse", "Townhouse"),
                            ("commercial", "Commercial"),
                        ],
                        default="single_family",
                        max_length=20,
                    ),
                ),
                ("bedrooms", models.PositiveSmallIntegerField(default=0)),
                (
                    "bathrooms",
                    models.DecimalField(decimal_places=1, default=0, max_digits=3),
                ),
                ("sq_ft", models.PositiveIntegerField(default=0)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "current_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="accounts.household",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "properties",
            },
        ),
    ]
