spec:
  name: zhub
  region: nyc
  databases:
    - engine: PG
      name: zhub-db
      num_nodes: 1
      size: db-s-dev-database
      version: "16"
  jobs:
    - name: zhub-migrate
      kind: PRE_DEPLOY
      github:
        repo: dunlapwr/zbase
        branch: main
        deploy_on_push: false
      run_command: python manage.py migrate --noinput
      instance_size_slug: basic-xxs
      envs:
        - key: DJANGO_SECRET_KEY
          scope: RUN_AND_BUILD_TIME
          type: SECRET
        - key: DJANGO_SETTINGS_MODULE
          scope: RUN_AND_BUILD_TIME
          value: zhub.settings.production
        - key: DATABASE_URL
          scope: RUN_AND_BUILD_TIME
          value: ${zhub-db.DATABASE_URL}
  services:
    - name: zhub-web
      github:
        repo: dunlapwr/zbase
        branch: main
        deploy_on_push: true
      build_command: python manage.py collectstatic --noinput
      run_command: gunicorn zhub.wsgi:application --bind 0.0.0.0:8080 --workers 2 --access-logfile - --error-logfile -
      http_port: 8080
      instance_count: 1
      instance_size_slug: basic-xxs
      envs:
        - key: DJANGO_SECRET_KEY
          scope: RUN_AND_BUILD_TIME
          type: SECRET
        - key: DEBUG
          scope: RUN_AND_BUILD_TIME
          value: "False"
        - key: DJANGO_SETTINGS_MODULE
          scope: RUN_AND_BUILD_TIME
          value: zhub.settings.production
        - key: DJANGO_ALLOWED_HOSTS
          scope: RUN_AND_BUILD_TIME
          value: ${APP_DOMAIN}
        - key: DATABASE_URL
          scope: RUN_AND_BUILD_TIME
          value: ${zhub-db.DATABASE_URL}
